FROM alpine:latest

ARG PB_VERSION=0.22.0

RUN apk add --no-cache \
    unzip \
    ca-certificates

# download and unzip PocketBase
ADD https://github.com/pocketbase/pocketbase/releases/download/v${PB_VERSION}/pocketbase_${PB_VERSION}_linux_amd64.zip /tmp/pb.zip
RUN unzip /tmp/pb.zip -d /pb/

# uncomment to copy the local pb_migrations dir into the image
COPY ./pb_migrations /pb/pb_migrations

# uncomment to copy the local pb_data dir into the image (changed from pb_hooks for clarity)
COPY ./pb_data /pb/pb_data

EXPOSE 8090

# start PocketBase on all interfaces to make it accessible from other containers
CMD ["/pb/pocketbase", "serve", "--http=0.0.0.0:8090"]
